name: CI and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/Installer.csproj
    - name: Publish x64 application
      run: dotnet publish -r win-x64 -c Release --self-contained true src/TorrentStream.csproj
    - name: Publish arm64 application
      run: dotnet publish -r win-arm64 -c Release --self-contained true src/TorrentStream.csproj
    - name: Upload x64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows64
        path: src/bin/Release/net8.0/win-x64/publish/TorrentStream.exe
    - name: Upload arm64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windowsarm64
        path: src/bin/Release/net8.0/win-arm64/publish/TorrentStream.exe
