name: CI and Release

on:
  push:
    branches: [ "main" ]

jobs:
  windows64:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Download Sciter
      run: wget https://github.com/trueromanus/TorrentStream/releases/download/1.0.1.12/sciterbin.zip
    - name: Extract zip
      uses: ihiroky/extract-action@v1
      with:
          file_path: sciterbin.zip
          extract_dir: sciterbin
    - name: Restore dependencies
      run: dotnet restore src/TorrentStream.csproj
    - name: Publish x64 application
      run: dotnet publish -r win-x64 -c Release --self-contained true src/TorrentStream.csproj
    - name: Publish arm64 application
      run: dotnet publish -r win-arm64 -c Release --self-contained true src/TorrentStream.csproj
    - name: Upload x64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows64
        path: src/bin/Release/net9.0/win-x64/publish/TorrentStream.exe
    - name: Upload arm64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windowsarm64
        path: src/bin/Release/net9.0/win-arm64/publish/TorrentStream.exe       
