name: CI and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  macos64:
    runs-on: macos-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/TorrentStream.csproj
    - name: Publish x64 application
      run: dotnet publish -r osx-x64 -c Release --self-contained true src/TorrentStream.csproj
    - name: Publish arm64 application
      run: dotnet publish -r osx-arm64 -c Release --self-contained true src/TorrentStream.csproj
    - name: Upload x64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos64
        path: src/bin/Release/net8.0/osx-x64/publish/TorrentStream
    - name: Upload arm64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macosarm64
        path: src/bin/Release/net8.0/osx-arm64/publish/TorrentStream
        
  windows64:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/TorrentStream.csproj
    - name: Publish x64 application
      run: dotnet publish -r win-x64 -c Release --self-contained true src/TorrentStream.csproj
    - name: Publish arm64 application
      run: dotnet publish -r win-arm64 -c Release --self-contained true src/TorrentStream.csproj
    - name: Upload x64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows64
        path: src/bin/Release/net8.0/win-x64/publish/TorrentStream.exe
    - name: Upload arm64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windowsarm64
        path: src/bin/Release/net8.0/win-arm64/publish/TorrentStream.exe
        
  linux64:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt get packages
      run: sudo apt-get install -y binutils-aarch64-linux-gnu gcc-multilib libc6-dev
    - name: Restore dependencies
      run: dotnet restore src/TorrentStream.csproj
    - name: Publish x64 application
      run: dotnet publish -r linux-x64 -c Release --self-contained true src/TorrentStream.csproj
    - name: Publish arm64 application
      run: dotnet publish -r linux-arm64 -c Release --self-contained true src/TorrentStream.csproj        
    - uses: actions/upload-artifact@v3
      with:
        name: linux64
        path: src/bin/Release/net8.0/linux-x64/publish/TorrentStream
    - uses: actions/upload-artifact@v3
      with:
        name: linuxarm64
        path: src/bin/Release/net8.0/linux-arm64/publish/TorrentStream
